// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQq-rzz8jD3qMib604GrwHI5NWOkMglEg',
    appId: '1:841915266947:web:8405544a0c7215d84f68b6',
    messagingSenderId: '841915266947',
    projectId: 'krakibak-5a0de',
    authDomain: 'krakibak-5a0de.firebaseapp.com',
    storageBucket: 'krakibak-5a0de.firebasestorage.app',
    measurementId: 'G-SQK0R0604D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSv-lhreqGtuxwa03vpqCMhvN59XWiPY',
    appId: '1:841915266947:android:3c0bc231887c3ebd4f68b6',
    messagingSenderId: '841915266947',
    projectId: 'krakibak-5a0de',
    storageBucket: 'krakibak-5a0de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy6iQDo42F5pdjiaBNVz8BbxE3CQ3oCdw',
    appId: '1:841915266947:ios:cd389f8572099fa74f68b6',
    messagingSenderId: '841915266947',
    projectId: 'krakibak-5a0de',
    storageBucket: 'krakibak-5a0de.firebasestorage.app',
    iosBundleId: 'com.example.nha228',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy6iQDo42F5pdjiaBNVz8BbxE3CQ3oCdw',
    appId: '1:841915266947:ios:cd389f8572099fa74f68b6',
    messagingSenderId: '841915266947',
    projectId: 'krakibak-5a0de',
    storageBucket: 'krakibak-5a0de.firebasestorage.app',
    iosBundleId: 'com.example.nha228',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQq-rzz8jD3qMib604GrwHI5NWOkMglEg',
    appId: '1:841915266947:web:a53f7be0b0e4114f4f68b6',
    messagingSenderId: '841915266947',
    projectId: 'krakibak-5a0de',
    authDomain: 'krakibak-5a0de.firebaseapp.com',
    storageBucket: 'krakibak-5a0de.firebasestorage.app',
    measurementId: 'G-K0P1FW886P',
  );
}
